### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by olegam**
Added support for adding dyci as a dependency using Carthage. Right now you can add dyci to your Cartfile using this line:
```
git "git@github.com:olegam/dyci-main.git" "master"
```

### CODE REVIEW

**Comment by PaulTaykalo** [comment]
Am Kind'a new for Carthage. Is it developer responsibilty to integrate library to his project after it will be downloaded by Carthage?

**Comment by olegam** [comment]
I highly recommend watching this talk by Justin Spahr-Summers: http://realm.io/news/swift-dependency-management-with-carthage/.

Carthage fetches the dependencies in a so-called Cartfile and builds a framework for each. The developer will manually drag the frameworks into his project once. But when the dependencies are updated the developer only needs to run `carthage update`.

**Comment by PaulTaykalo** [comment]
If so, then I thinkg the Project should be moved under  
`/Dynamic Code Injection/dyci-carthage`  
Since there already `dyci-framework`, `dyci-example` and others

**Comment by olegam** [comment]
The problem is that the project file must be in the root for Carthage to work. I know this is a little messy, but since I put Carthage in the name of the project file it should hopefully be less confusing what the file is for.

**Comment by PaulTaykalo** [comment]
Well, as i can see this one is seems to be working
`git "https://github.com/DyCI/dyci-main.git" "feature/carthage"`
https://github.com/DyCI/dyci-main/tree/feature/carthage/Dynamic%20Code%20Injection  
@olegam  Please confirm

**Comment by olegam** [comment]
Yes this works!
I wonder how Carthage figures out to build the correct framework..

**Comment by PaulTaykalo** [comment]
@olegam As far as I found https://github.com/Carthage/Carthage/issues/210#issuecomment-67040112 it searchs the root-most :) project. So if there won't be radical structure changes, it should work

**Comment by olegam** [comment]
Great. Thanks!

**Comment by PaulTaykalo** [comment]
Thanks for the pull request :)

**Pull request merged**
