### PR TITLE
Added a macro 'DYCIMacro.h' and some example codes to 'dyci-example'

### PR DESCRIPTION
**Pull request by metasmile**
Please refer to the comments inside of code :)

### CODE REVIEW

**Comment by PaulTaykalo** [comment]
First of all thanks for your input.  
Second - you're trying to pull to old, developer branch, when latest changes were made in master branch    
Third - While the idea and macroses are great, I think that using these macroses will lead to dependency on *dyci* iself. Which I want to prevent.  I don't want to introduce some specific secret macroses. Currently, your code will work event if dyci library will be removed from the project. If we add these Macroses, we'll push user's to use them, and this will lead to direct dependency on dyci as library.

So at least what I'll suggest is to rename it to something _like_ **DYCI_Debug_Macro.h**

**Comment by metasmile** [comment]
ok, I understood~

**Comment by PaulTaykalo** [comment]
As about this neat trick with try-catch - I think that there's a way to add it in dyci itself, and revert to default, empty implementation of `-(void)updateOnInjection` in case if exception happens

**Comment by metasmile** [comment]
wow, I have worked same as your recently commit :)) 
And yes, I'll try to think from now onwards about additional work while I use to my project.
thanks to you and this tool~

**Pull request closed without merging**
